namespace Agent.Core;

/// <summary>
/// Predicted world state after executing an action, plus confidence.
/// Generated by the WorldModel's rule-based prediction engine.
/// </summary>
public sealed record PredictionState(
    string ActionTool,
    IReadOnlyDictionary<string, object?> ActionArgs,
    Position? PredictedPosition,
    int PredictedHealth,
    int PredictedFood,
    IReadOnlyDictionary<string, int> PredictedInventory,
    double Confidence,           // 0.0 – 1.0
    string Rationale);           // human-readable explanation
