namespace Agent.Construction;

/// <summary>
/// Storage for named build blueprints backed by MemorySmith pages.
/// Blueprints can be imported (Litematica schematics), hand-crafted
/// (markdown pages), or procedurally generated by an IArchitect.
/// </summary>
public interface IBlueprintRepository
{
    Task<Blueprint?> GetAsync(string blueprintId, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<Blueprint>> SearchAsync(string query, CancellationToken cancellationToken = default);
    Task<string> SaveAsync(Blueprint blueprint, CancellationToken cancellationToken = default);
}
